### ISSUE TITLE
Questions

### ISSUE THREAD

**Issue by ghost** [roskakori/swiftmess#1]
Hi!

Great initiative, this.

I have some questions:
1. What are the goals of the project? 
   Will it also involve encoding swift messages?
   The hard part with making the messages, by the way, is knowing when to put what in each field and all the frankly silly stuff on how to format account numbers, rules and all that, not the format itself(even though that is strange too).  
2.  How ambitious is it? What message types are you considering to support?
   I once implemented a SWIFT encoder commercially a  while ago(not in python), so I suppose it can't be only for the fun of it. :-)
3. Less important question: There has been, since about 2002, a proposed XML variant of MT 15022 coming. Now the financial industry is certainly not the fastest to pick things up and I frankly don't know what happened to it(will 20022 be it?), but are you thinking of stuff like that. I am thinking code-wise? Or will that be another implementation altogether?
4. The licence. Using GPL3 will be a significant problem if someone wants to use this in a financial business application. These applications, or at least parts of them, are basically always closed source so no one will be able to use this module in those applications. And most, if not all, that would like to contribute to a project like this would use it there. Would you consider using LGPL instead?

Cheers, Zig007

**Comment by roskakori** [comment]
Hi zig,

thanks for your interest in swiftmess at this early stage.

Concerning your questions:
1. At the moment swiftmess's goal is to offer a library that can:
   1. ...read SWIFT messages and reports as needed by my employer.
   2. ...easily be extended to read other similar messages and reports.
   3. ...detect errors in data and report them in a specific and reasonably comprehensible way.
   
   There are currently no plans to support building and writing messages though I welcome contributions.
   
   I mainly did swiftmess because we need something like it at my job. I could not find any open source Python library to do that, so I considered we might as well start one.
2. Currently swiftmess supports reading MT536 messages and CE260. Support for CE280 reports probably will be added along the way. The base parsers are intended to be flexible enough to support more messages with a reasonable amount of effort in the future.
3. We do not have any requirements to support XML yet, so there are no specific plans for the time being. The current SWIFT specification talks about XML, though I'm not sure who actually uses it.
4. It's LGPL3 ("lesser GPL"), so you can use it in closed source financial business application. In fact, that's how we use it. I do however want to encourage people to contribute any improvements to the library such as support for additional messages. I don't think anyone gains any big advantage on the market by being able to read SWIFT messages.

Cheers, Thomas.

**Comment by ghost** [comment]
1, 2: Sounds great.
3: I will try and directly import some of the message types of MT 20022 (
http://www.iso20022.org/message_archive.page) through some modelling tool
and see what comes out, it should actually be easier than 15022. In 15022,
a million kinds of settlement processes has been mashed into the same
message types, which makes it a b*tch to find out where to put what
information as the banks seem do this based on convention, rather than
standard. It is not inherent of the 15022 standard itself what happens in
each situation, which seems to have been attempted in 20022, which is
probably why it is so huge.
4. Oh, I am sorry! I saw that now. No, there is not big advantage, but it
is good for python.

I will see what I can contribute with.

//Nicklas
